language: perl6
perl6:
  - latest

install:
  - rakudobrew build zef

env:
  - PATH="/home/travis/.rakudobrew/moar-nom/install/share/perl6/site/bin:$PATH"

script:
  - zef install . && spit eval 'say "hello world"'
